### ISSUE TITLE
Incorrect detection in `_is a letter`

### ISSUE THREAD

**Issue by tdhsmith** [AvailLang/Avail#142]
`_is a letter` doesn't know about Latin Extended-C, among others. Yes, I do know that the method doesn't claim to be complete, but this absence is ever-so-slightly more frustrating than baseline since a number of its members can be gotten to by means of applying `uppercase_` to a character Avail _does_ identify as a letter. (in my case, U+0251 `ɑ` → U+2C6D `Ɑ`)

A long time ago, I suggested updating Avail's character and string tools to align with and source from the Unicode Character Database. That's something I'm still interested in helping accomplish, though I'm a little wary about what would be the most Avail-y way of approaching it, since it would presumably involve machine-generated code which takes the UCD data files as input (in order to avoid a strict pairing between Unicode and Avail standard library versions).

**Comment by tdhsmith** [comment]
Also, jumping back to the original issue, I assume the definition of "letter" to Avail would then be updated to some combination of its General Categories... presumably all of the `Lu`, `Ll`, `Lt`, `Lm`, `Lo`?

I didn't get a chance to thoroughly compare the existing ranges with the general category lists, but it definitely looks like it already includes a number of ideographs (`∈ Lo`) which is one of the grayer areas. Though I personally feel deeming them _not_ letters would always have some smell of anglocentrism.

**Comment by toddATavail** [comment]
Yes, I think that the correct answer to is generate `Characters.avail` — or some new input module that would be used by it — from the UCD data files, to ensure canonicity by construction. To support our transition to Kotlin as an implementation language, the code generator for this should be written in Kotlin., and we would want to add a new build rule to Gradle to run the code generator at the appropriate times.

Our team is stretched thin at the moment — we are currently building an IDE (Anvil) to support another active client, and it entails significant engagement. I have two questions:

* Can you give us a sense of urgency for this fix?
* Are you able to provide a fix (and merge request) for the problem(s) yourself as a stopgap?

I need this information in order to decide the priority of your request.

**Comment by markATavail** [comment]
In September (2019), I added a primitive and support code for extracting character types, which you can find at the end of Characters.avail.  However, I didn't go back and update the hard-coded lowercase and uppercase tables in the same file, nor the type test methods (partly to avoid breaking MCP).  It looks like you could use "_'s⁇character type number" and check if it's in [1..5] (the "L*" character types), essentially as you suggested.

If you update "_is a letter" in this way and check that it doesn't break your application or any Avail unit tests, we'd be happy to review it and merge it into master.

**Comment by toddATavail** [comment]
@tdhsmith, this has been resolved in `development`. I would advise that you migrate forward to `development` if possible, in order to leverage significant functionality and performance enhancements over `master` (or whatever legacy version you might be using). If you can't migrate forward to `development`, then you may want to cherry pick the changes onto your version.

**Comment by tdhsmith** [comment]
Thanks all! I mentioned to Todd in a private discussion that this was found as part of dayjob work but was ultimately for personal use. In that scenario I can definitely switch to development branch; I had forgotten to check there during my initial report, apologies.

(MCP remains pinned at a specific commit hash, FYI. Will likely remain that way until I find a significant amount of free work time to upgrade it.)
