### ISSUE TITLE
Generalize ModuleRoot to be accessed via a URI

### ISSUE THREAD

**Issue by richATavail** [AvailLang/Avail#194]
Presently an Avail `ModuleRoot` is presumed to originate from the local file system. Generalize a `ModuleRoot` to utilize a URI that determines where the `ModuleRoot` is stored. This will interact with a URI-scheme specific implementation of the `FileManager` to provide access to the contents of the `ModuleRoot`. This should enable an `AvailRuntime` to have loaded module roots loaded from the local file system, networked file systems, database, network API, etc.

Once complete, the `AvailServer` should expect well formed URIs when creating/opening `ModuleRoot`s for the Avail `Session`.

**Comment by richATavail** [comment]
Updating `ModuleRoot` to accept a `URI` instead of a `File` will let us generalize the origin of the source, however the `Repository` is also represented by a `File`. The repository being the build artifact, where exactly should it exist? Locally?

**Comment by markATavail** [comment]
Yes, the repository files should be on the local filesystem.  The repository files are just a local cache of previous compilations.  Other than locking issues, two runtimes running on different machines could in theory even use the same repository, since the result of each module compilation should be semantically identical.
